[package]
name = "staking"
version = "1.0.0"
authors = []

[addresses]
dev='0x3790240aa9d7400d42d99181e0f2364c84d7ef8e9639b99151132a631b11e7d4'
collection_creator='0x69caa204288ca6d19f455247fbdf1c7dae0e3c4fb2e30a71e92d4e0e3bec32a1'
old_collection_creator='0x45505eafafdb076e35c76d2805e8461b78b5443c4876e87014232dacaff351db'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token", rev = "mainnet" }
permissions = {local = "../permissions"}
